# Short tutorial for Jupyter Notebooks

This notebook guides the user through using Jupyter notebooks for this assignment. It is intended towards beginners and is meant to be an introduction. It is **not** a comprehensive breakdown of all the features of Jupyter Notebooks and does not explain their inner workings. 

Jupyter Notebooks consist of cell blocks. Each of these cell blocks can hold code, markdown, and Raw NBConvert. This is a Markdown cell. 

Each cell can be in two modes of operation:

1. Command mode: 

In command mode, the cell is just selected and there is no blinking cursor in the cell. From here you can change cell types, add new cells, delete cells etc. To go into command mode, click a cell on the left side margin.    <br />


2. Edit mode:

When the cell is in Edit mode, you should see a blinking cursor in the cell. In this mode, you can edit the contents of the cell. To edit a code cell, click the cell body and begin typing. To edit a Markdown cell, click the cell body twice.  <br />   <br />

You can switch a cell from Edit mode to Command mode by pressing the `Esc` key. Press the `Enter` key to switch between Command mode and Edit mode. 

You should **not** modify Raw NBConvert cells.

In [2]:
# This is a code cell. 

To change a markdown cell to a code cell, press `Y` in Command mode. 

Change the following marksdown cell to a code cell.

### Markdown cell
print("Hello!")

To conver it back to Markdown, press `M` in command mode. 

You can run each cell in 3 ways:

1. Press `Shift + Enter`: This will run the selected cell and select the next cell. If it is the last cell in the notebook, it will create a new Code cell and select it.

2. Press `Ctrl + Enter`: This will run the select cell and not move to the next one. 

3. You can select an option from the "Cell" dropwdown at the top. <br />   <br />

In [4]:
import numpy as np

Let's see the result of the follwing cell:

In [5]:
a = np.array([1, 2, 3, 4, 5])
b = 5
a*b

array([ 5, 10, 15, 20, 25])

As you can see, running a code cell is almost exactly like pasting the code snippet into file and running it. However, there is one important difference with Jupyter Notebooks.

## Out-of-order execution

In Jupyter notebooks, you can run pieces of code out-of-order unlike in a Python script. What this means is that you could run the cells of a notebook in any order. <br />   <br />

This can be done because the kernel saves all the variables and functions that have been defined in memory. So if you were to create a function and run the cell, but later change your mind and delete it, the function will still persist in memory and you can still make calls to it.   <br />   <br />

Often this leads to bad references to functions and variables. To check for this, you can save the notebook `Ctrl + S`, and click on "Kernel" in the top menu. Select "Restart & Run All". This will restart the kernel and run all cells in order. <br />   <br />

Let's see an example of when out-of-order execution can lead to unexpected/problematic behaviour.

In [8]:
a*b    #Gives the same result as before

array([ 6, 12, 18, 24, 30])

In [7]:
b += 1  #Run the previous cell again. You will see a different output. 

In [12]:
a * c #This will throw an error the first time you run it.

array([ 3,  6,  9, 12, 15])

In [11]:
c = 3   # Run this and run the previous cell again. It will produce the result of a * 3. 

## Manipulating cells

In command mode, if you press:


Should remember:

- `A`:a new cell will be created above the current one. 
- `B`: new cell created bellow the current one. 
- `D, D`: Press `D` twice to delete a cell.   <br />   <br />

Good to know:
- `C`: Copy a cell
- `V`: Paste a cell
- `X`: Cut a cell
- `Z`: Undo cell manipulation. 

Often I will just cut a cell instead of deleting it because it is just one key press. 

You can also use arrow keys to navigate in Command mode.

Try adding cells above and below this one.

## Running Terminal commands

Jupyter notebooks support running terminal commands within code cells. To do so, preface your terminal command with an `!`.

In [13]:
!echo "Hello World!"

Hello World!


## Helpful things to remember


You can, at anytime, press `Ctrl+Shift+P` to pull up the command palette. You can also search through the command palette. <br />   <br />




To view Keyboard Shortcuts, you can press `H` in command mode. This contains a comprehensive list of all the commands you can run using keyboard shortcuts in Command mode and Edit modes.   <br />   <br />

You can interrupt a cell execution by pressing `I, I` i.e. pressing `I` twice while in command mode. 

## Fin.

You are welcome to experiment in this notebook and play around with it. You don't have to submit it. Hopefully, it has helped you get a bit familiar with Jupyter notebooks. 

If you have any suggestions or feedback for improving it, please let us know.